server:  
  port: 8081


spring:
  application:
    name: sa-gateway
  cloud:
    gateway:
      routes:
      - id: sa-mongo
        uri: lb://sa-mongo/
        predicates:
        - Path=/mongo/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
            - GET
            - POST
logging:
  level:
    org.springframework.web: ERROR

  
eureka:
  instance:
    statusPageUrl: http://0.0.0.0:${server.port}/info
    healthCheckUrl: http://0.0.0.0:${server.port}/health
    homePageUrl: http://0.0.0.0:${server.port}
  client:
    serviceUrl:
      defaultZone: http://0.0.0.0:8761/eureka/