server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
      - id: display-ui
        uri: http://localhost:8082/
        predicates:
        - Path=/ui/**
      - id: display-video
        uri: http://localhost:8083/
        predicates:
        - Path=/video/**

#logging:
#  level:
#    org.springframework: DEBUG
#    org.springframework.web: ERROR

eureka:
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 5
  client:
    fetch-registry: true
    registry-fetch-interval-seconds: 5