server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
      - id: sa-mysql
        uri: http://localhost:8082/
        predicates:
        - Path=/ui/**
      - id: sa-mongo
        uri: http://localhost:8083/
        predicates:
        - Path=/mongo/**
      - id: sa-message
        uri: http://localhost:8084/
        predicates:
        - Path=/email/**
      - id: sa-user
        uri: http://localhost:8085/
        predicates:
        - Path=/user/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
            - GET
            - POST
#logging:
#  level:
#    org.springframework: DEBUG
#    org.springframework.web: ERROR

eureka:
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 5
  client:
    fetch-registry: true
    registry-fetch-interval-seconds: 5