version: "3.3"

services:

   sa-angular:
      image: faizulnoor/sa-angular
      container_name: sa-angular
      networks:
         - sanetwork
      ports:
        - "80:80"

   sa-discovery:
      image: faizulnoor/sa-discovery
      container_name: sa-discovery
      environment: 
         - eureka.client.serviceUrl.defaultZone=http://sa-discovery:8761/eureka/
      networks:
         - sanetwork
      ports:
        - "8761:8761"

   sa-gateway:
      image: faizulnoor/sa-gateway
      container_name: sa-gateway
      environment: 
         - eureka.client.serviceUrl.defaultZone=http://sa-discovery:8761/eureka/
      networks:
         - sanetwork
      ports:
        - "8081:8081"

   sa-user:
      image: sa-user
      container_name: faizulnoor/sa-user
      environment: 
         - eureka.client.serviceUrl.defaultZone=http://sa-discovery:8761/eureka/
      networks:
         - sanetwork 
      ports:
        - "8085:8085"
        
#   sa-mysql:
#      image: sa-mysql
#      container_name: sa-mysql
#      environment: 
#         - eureka.client.serviceUrl.defaultZone=http://sa-discovery:8761/eureka/
#      networks:
#         - sanetwork 
#      ports:
#        - "8082:8082"
      #extra_hosts:
      #  - "host.docker.internal:172.17.0.1"
      
#  sa-mongo:
#      image: sa-mongo
#      container_name: sa-mongo
#      environment: 
#         - eureka.client.serviceUrl.defaultZone=http://sa-discovery:8761/eureka/
#      networks:
#         - sanetwork 
#      ports:
#        - "8083:8083"
      #extra_hosts:
      #  - "host.docker.internal:172.17.0.1"
        

         
networks:
    sanetwork:
     driver: bridge