version: "3.3"

services:

   sa-angular:
      image: faizulnoor/sa-angular
      container_name: sa-angular
      networks:
         - sanetwork
      ports:
        - "80:80"

   sa-discovery:
      image: faizulnoor/sa-discovery
      container_name: sa-discovery
      environment:
         - eureka.client.serviceUrl.defaultZone=http://sa-discovery:8761/eureka/
      networks:
         - sanetwork
      ports:
        - "8761:8761"
      #volumes:
      #  - /home/ubuntu/mytemp:/tmp

   sa-gateway:
      image: faizulnoor/sa-gateway
      container_name: sa-gateway
      environment:
         - eureka.client.serviceUrl.defaultZone=http://sa-discovery:8761/eureka/
      networks:
         - sanetwork
      ports:
        - "8081:8081"
      #volumes:
      #  - /home/ubuntu/mytemp:/tmp

   sa-user:
      image: faizulnoor/sa-user
      container_name: faizulnoor/sa-user
      environment: 
         - eureka.client.serviceUrl.defaultZone=http://sa-discovery:8761/eureka/
      networks:
         - sanetwork 
      ports:
        - "8085:8085"
        
   sa-mysql:
      image: faizulnoor/sa-mysql
      container_name: sa-mysql
      environment: 
         - eureka.client.serviceUrl.defaultZone=http://sa-discovery:8761/eureka/
      networks:
         - sanetwork 
      ports:
        - "8082:8082"

   sa-mongo:
      image: faizulnoor/sa-mongo
      container_name: sa-mongo
      environment:
        - eureka.client.serviceUrl.defaultZone=http://sa-discovery:8761/eureka/
      networks:
        - sanetwork
      ports:
        - "8083:8083"
      extra_hosts:
        - "mongoservice:172.17.0.1"
      #volumes:
      #  - /home/ubuntu/mytemp:/tmp
        
networks:
    sanetwork:
     driver: bridge
    host:
      #driver: host 
     external: true